//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEvents
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int Id_message { get; set; }
        public System.DateTime datatime { get; set; }
        public int id_message_user { get; set; }
        public int Id_message_type_message { get; set; }
        public string message_text { get; set; }
        public int Id_message_event { get; set; }
        public byte[] media_content { get; set; }
        public bool processed { get; set; }
        public int Id_message_message_categories { get; set; }
    
        public virtual message_categories message_categories { get; set; }
        public virtual message_processing message_processing { get; set; }
        public virtual popular_messages popular_messages { get; set; }
        public virtual type_message type_message { get; set; }
        public virtual user user { get; set; }
    }
}
