//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEvents
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int Id_user { get; set; }
        public string first_name { get; set; }
        public string second_name { get; set; }
        public string Patronomyc { get; set; }
        public byte[] Telephone { get; set; }
        public string Email { get; set; }
        public Nullable<int> Age { get; set; }
        public int Id_user_federal_districts { get; set; }
    
        public virtual FederalDistricts FederalDistricts { get; set; }
        public virtual messages messages { get; set; }
    }
}
